#Database
spring:
  sql:
    init-moode: always
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: web_service
    url: jdbc:postgresql://192.168.100.27:3305/my_db
    password: pass_secret
    hikari:
      maximum-pool-size: 2
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: 'true'
    show-sql: 'true'
