services:
  db:
    image: mysql
    container_name: mysql_my_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: web_service
      MYSQL_DATABASE: my_db
      MYSQL_PASSWORD: pass_secret
      MYSQL_ROOT_PASSWORD: pass_secret
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3305:3306
    expose:
      - 3305
