version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql_dev
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: web_service
      MYSQL_PASSWORD: pass_secret
      MYSQL_ROOT_PASSWORD: pass_secret
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
